theme: jekyll-theme-slate
title: mEntulimu
collections:
  jbo:
    output: true
    permalink: /:title-jbo.html
  liste:
    output: true
    permalink: /:title.html
    values:
      layout: liste
defaults:
  - scope:
      path: ""
      type: liste
    values:
      author: guskant
      author_url: http://photon.freeshell.org/

