theme: jekyll-theme-slate
markdown: kramdown
title: mEntulimu
author: guskant
author_url: http://photon.freeshell.org/
contact: mailto:gusni.kantu@gmail.com?Subject=mEntulimu
collections:
  jbo:
    output: true
    permalink: /:title-jbo.html
  liste:
    output: true
    permalink: /:title.html
  skina:
    output: true
    permalink: /:title.html
defaults:
  - scope:
      path: ""
      type: liste
    values:
      layout: post
