theme: jekyll-theme-slate
title: mEntulimu
author: guskant
author_url: http://photon.freeshell.org/
collections:
  jbo:
    output: true
    permalink: /:title-jbo.html
  liste:
    output: true
    permalink: /:title.html
defaults:
  - scope:
      path: ""
      type: liste
    values:
      layout: post
